# Generated by Django 3.0.8 on 2020-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
