# Generated by Django 3.0.8 on 2020-08-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
